package com.myspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class brms implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public brms() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public brms(java.lang.String name) {
		this.name = name;
	}

}