package com.myspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class brms implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String knjk;

	private java.lang.Integer jn;

	public brms() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getKnjk() {
		return this.knjk;
	}

	public void setKnjk(java.lang.String knjk) {
		this.knjk = knjk;
	}

	public java.lang.Integer getJn() {
		return this.jn;
	}

	public void setJn(java.lang.Integer jn) {
		this.jn = jn;
	}

	public brms(java.lang.String name, java.lang.String knjk,
			java.lang.Integer jn) {
		this.name = name;
		this.knjk = knjk;
		this.jn = jn;
	}

}