package com.myspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class effeff implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean vdv;

	private java.math.BigInteger fe;

	private java.math.BigInteger xsx;

	private java.lang.Byte jb;

	private java.util.Date kn;

	private java.math.BigDecimal xssad;

	private java.lang.Integer cdvd;

	private java.lang.Byte efefeffef;

	public effeff() {
	}

	public java.lang.Boolean getVdv() {
		return this.vdv;
	}

	public void setVdv(java.lang.Boolean vdv) {
		this.vdv = vdv;
	}

	public java.math.BigInteger getFe() {
		return this.fe;
	}

	public void setFe(java.math.BigInteger fe) {
		this.fe = fe;
	}

	public java.math.BigInteger getXsx() {
		return this.xsx;
	}

	public void setXsx(java.math.BigInteger xsx) {
		this.xsx = xsx;
	}

	public java.lang.Byte getJb() {
		return this.jb;
	}

	public void setJb(java.lang.Byte jb) {
		this.jb = jb;
	}

	public java.util.Date getKn() {
		return this.kn;
	}

	public void setKn(java.util.Date kn) {
		this.kn = kn;
	}

	public java.math.BigDecimal getXssad() {
		return this.xssad;
	}

	public void setXssad(java.math.BigDecimal xssad) {
		this.xssad = xssad;
	}

	public java.lang.Integer getCdvd() {
		return this.cdvd;
	}

	public void setCdvd(java.lang.Integer cdvd) {
		this.cdvd = cdvd;
	}

	public java.lang.Byte getEfefeffef() {
		return this.efefeffef;
	}

	public void setEfefeffef(java.lang.Byte efefeffef) {
		this.efefeffef = efefeffef;
	}

	public effeff(java.lang.Boolean vdv, java.math.BigInteger fe,
			java.math.BigInteger xsx, java.lang.Byte jb, java.util.Date kn,
			java.math.BigDecimal xssad, java.lang.Integer cdvd,
			java.lang.Byte efefeffef) {
		this.vdv = vdv;
		this.fe = fe;
		this.xsx = xsx;
		this.jb = jb;
		this.kn = kn;
		this.xssad = xssad;
		this.cdvd = cdvd;
		this.efefeffef = efefeffef;
	}

}