package com.myspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class effeff implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean vdv;

	public effeff() {
	}

	public java.lang.Boolean getVdv() {
		return this.vdv;
	}

	public void setVdv(java.lang.Boolean vdv) {
		this.vdv = vdv;
	}

	public effeff(java.lang.Boolean vdv) {
		this.vdv = vdv;
	}

}