package com.myspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class effeff implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean vdv;

	private java.math.BigInteger fe;

	private java.math.BigInteger xsx;

	private java.lang.Byte jb;

	public effeff() {
	}

	public java.lang.Boolean getVdv() {
		return this.vdv;
	}

	public void setVdv(java.lang.Boolean vdv) {
		this.vdv = vdv;
	}

	public java.math.BigInteger getFe() {
		return this.fe;
	}

	public void setFe(java.math.BigInteger fe) {
		this.fe = fe;
	}

	public java.math.BigInteger getXsx() {
		return this.xsx;
	}

	public void setXsx(java.math.BigInteger xsx) {
		this.xsx = xsx;
	}

	public java.lang.Byte getJb() {
		return this.jb;
	}

	public void setJb(java.lang.Byte jb) {
		this.jb = jb;
	}

	public effeff(java.lang.Boolean vdv, java.math.BigInteger fe,
			java.math.BigInteger xsx, java.lang.Byte jb) {
		this.vdv = vdv;
		this.fe = fe;
		this.xsx = xsx;
		this.jb = jb;
	}

}