package com.myspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class vdvd implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public vdvd() {
    }




}