package com.myspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class vdvd implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Float csdfc;

	public vdvd() {
	}

	public java.lang.Float getCsdfc() {
		return this.csdfc;
	}

	public void setCsdfc(java.lang.Float csdfc) {
		this.csdfc = csdfc;
	}

	public vdvd(java.lang.Float csdfc) {
		this.csdfc = csdfc;
	}

}